""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" SETTINGS
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

exec 'source ' . expand('<sfile>:p:h') . '/settings.vim'

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" MAPPINGS
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

exec 'source ' . expand('<sfile>:p:h') . '/mappings.vim'

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" AUTOCOMMANDS
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

exec 'source ' . expand('<sfile>:p:h') . '/autocommands.vim'

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" PLUGIN SETTINGS
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" catppuccin
color catppuccin_frappe

" vim-highlightedyank
let g:highlightedyank_highlight_duration = 200

" Venter
nnoremap <leader>v :VenterToggle<CR>

" FZF
nnoremap <leader>fg :GFiles<CR>
nnoremap <leader>? :GFiles?<CR>
nnoremap <leader>rg :Rg<CR>

" Fugitive
nnoremap <leader>gc :Git commit<CR>
nnoremap <leader>gp :Git push<CR>

" YouCompleteMe
nnoremap <leader>jd :YcmCompleter GoTo<CR>

" ALE
let g:ale_fixers = { '*': ['remove_trailing_lines', 'trim_whitespace'] }
let g:ale_fix_on_save = 1
augroup ALE
    au!
    autocmd FileType ale-preview setlocal wrap
    autocmd FileType c let g:ale_c_clangtidy_extra_options='-clang-analyzer-security.insecureAPI.strcpy'
    autocmd BufEnter *.tsv execute 'if has_key(g:ale_fixers, "*") | unlet g:ale_fixers["*"] | endif'
augroup END
